MAX_INITIAL_QUERIES = 3
MAX_SUPPLEMENT_QUERIES = 2
MAX_RESEARCH_ROUNDS = 2
MAX_RESEARCH_LLM_CALLS = 3
MAX_RESEARCH_CANDIDATES = 24
MAX_FINAL_EVIDENCE_ITEMS = 10
MAX_QUERY_CHARS = 300
MAX_ASPECTS = 5
MAX_ASPECT_CHARS = 100
MAX_CANDIDATE_TEXT_CHARS = 1600
MAX_LLM_INPUT_CHARS = 40000
MAX_RESEARCH_OUTPUT_TOKENS = 3800
MAX_FINAL_ANSWER_CHARS = 4000
DEFAULT_RESEARCH_TIMEOUT_SECONDS = 180

PLANNER_MAX_TOKENS = 800
DECIDER_MAX_TOKENS = 1200
FINALIZER_MAX_TOKENS = 1800
